version: '3'
services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '8888:80'
    networks:
      - selenoid

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'
    networks:
      - selenoid

  opencart:
    image: docker.io/bitnami/opencart:4
    ports:
      - '8080:8080'
      - '443:8443'
    networks:
      - selenoid
    environment:
      - OPENCART_HOST=opencart:8080
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb

  tests:
    image: opencart-tests:latest
    build:
      dockerfile: tests/Dockerfile
    depends_on:
      - opencart
    networks:
      - selenoid
#    command: ./wait-for-it.sh opencart 8080 -- pytest -v /tests --opencart_url http://opencart:8080 --browser chrome --browser_version 127.0 --executor selenoid
    command: ./wait-for-it.sh opencart 8080 pytest -v /tests --launch_mode remote --vnc
    container_name: opencart-tests

networks:
  selenoid:
    driver: bridge
    external: true

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local